spring.application.name=HelloWorldApp

# Server Port
server.port=8081

# Show Spring Boot startup banner
spring.main.banner-mode=console

# Logging Level
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG